//! The starter pack: the fixed set of card definitions a new deck is dealt
//! from. Draw randomizes the *order* cards come out in; this is what defines
//! *which* cards exist to be drawn.

use crate::card::{Card, CardType, Rarity, TargetType};

pub fn starter_pack() -> Vec<Card> {
    vec![
        Card::new(
            "quick_jab",
            "Quick Jab",
            1,
            Rarity::Common,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 6 damage.",
        ),
        Card::new(
            "quick_jab_2",
            "Quick Jab",
            1,
            Rarity::Common,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 6 damage.",
        ),
        Card::new(
            "buffer_overflow",
            "Buffer Overflow",
            2,
            Rarity::Common,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 10 damage.",
        ),
        Card::new(
            "firewall",
            "Firewall",
            1,
            Rarity::Common,
            TargetType::SelfTarget,
            CardType::Skill,
            "Gain 8 block.",
        ),
        Card::new(
            "firewall_2",
            "Firewall",
            1,
            Rarity::Common,
            TargetType::SelfTarget,
            CardType::Skill,
            "Gain 8 block.",
        ),
        Card::new(
            "encrypt",
            "Encrypt",
            1,
            Rarity::Common,
            TargetType::SelfTarget,
            CardType::Skill,
            "Gain 5 block. Draw a card.",
        ),
        Card::new(
            "overclock",
            "Overclock",
            2,
            Rarity::Uncommon,
            TargetType::SelfTarget,
            CardType::Power,
            "Gain 1 energy at the start of each turn.",
        ),
        Card::new(
            "backdoor",
            "Backdoor",
            2,
            Rarity::Uncommon,
            TargetType::Enemy,
            CardType::Skill,
            "Reduce noise generated this turn by 5.",
        ),
        Card::new(
            "ransomware",
            "Ransomware",
            3,
            Rarity::Rare,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 18 damage. Generates 4 noise.",
        ),
        Card::new(
            "zero_day_exploit",
            "Zero-Day Exploit",
            3,
            Rarity::Rare,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 14 damage. Ignores block.",
        ),
        Card::new(
            "ghost_protocol",
            "Ghost Protocol",
            2,
            Rarity::Rare,
            TargetType::SelfTarget,
            CardType::Skill,
            "This turn generates no noise.",
        ),
        Card::new(
            "system_crash",
            "System Crash",
            4,
            Rarity::Legendary,
            TargetType::AllEnemies,
            CardType::Attack,
            "Deal 12 damage to all enemies. Shutdown for 1 turn.",
        ),
        Card::new(
            "glitch",
            "Glitch",
            0,
            Rarity::Common,
            TargetType::None,
            CardType::Curse,
            "Unplayable. Clutters your hand.",
        ),
        Card::new(
            "corrupted_data",
            "Corrupted Data",
            1,
            Rarity::Common,
            TargetType::None,
            CardType::Status,
            "Ethereal. Exhausts if not played this turn.",
        ),
        Card::new(
            "quick_jab_3",
            "Quick Jab",
            1,
            Rarity::Common,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 6 damage.",
        ),
        Card::new(
            "buffer_overflow_2",
            "Buffer Overflow",
            2,
            Rarity::Common,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 10 damage.",
        ),
        Card::new(
            "encrypt_2",
            "Encrypt",
            1,
            Rarity::Common,
            TargetType::SelfTarget,
            CardType::Skill,
            "Gain 5 block. Draw a card.",
        ),
        Card::new(
            "ping_flood",
            "Ping Flood",
            1,
            Rarity::Common,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 4 damage. Draw a card.",
        ),
        Card::new(
            "patch",
            "Patch",
            1,
            Rarity::Common,
            TargetType::SelfTarget,
            CardType::Skill,
            "Remove all debuffs.",
        ),
        Card::new(
            "keylogger",
            "Keylogger",
            1,
            Rarity::Uncommon,
            TargetType::Enemy,
            CardType::Skill,
            "Preview the enemy's next intent.",
        ),
        Card::new(
            "rootkit",
            "Rootkit",
            3,
            Rarity::Uncommon,
            TargetType::SelfTarget,
            CardType::Power,
            "Gain 2 block at the start of each turn.",
        ),
        Card::new(
            "phishing_email",
            "Phishing Email",
            1,
            Rarity::Common,
            TargetType::Enemy,
            CardType::Skill,
            "Enemy loses 2 block.",
        ),
        Card::new(
            "ddos",
            "DDoS",
            2,
            Rarity::Uncommon,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 8 damage. Generates 6 noise.",
        ),
        Card::new(
            "man_in_the_middle",
            "Man in the Middle",
            2,
            Rarity::Rare,
            TargetType::Enemy,
            CardType::Skill,
            "Redirect the enemy's next attack to another enemy.",
        ),
        Card::new(
            "trojan_horse",
            "Trojan Horse",
            2,
            Rarity::Rare,
            TargetType::Enemy,
            CardType::Attack,
            "Deal 8 damage now, 8 more next turn.",
        ),
        Card::new(
            "cold_boot_attack",
            "Cold Boot Attack",
            1,
            Rarity::Rare,
            TargetType::SelfTarget,
            CardType::Skill,
            "Gain 10 block. Exhaust.",
        ),
        Card::new(
            "black_ice",
            "Black ICE",
            2,
            Rarity::Legendary,
            TargetType::SelfTarget,
            CardType::Power,
            "Whenever you take damage, deal 5 damage back.",
        ),
        Card::new(
            "static_noise",
            "Static Noise",
            0,
            Rarity::Common,
            TargetType::None,
            CardType::Curse,
            "Unplayable.",
        ),
        Card::new(
            "dead_pixel",
            "Dead Pixel",
            0,
            Rarity::Common,
            TargetType::None,
            CardType::Status,
            "Unplayable. Ethereal.",
        ),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn starter_pack_has_twenty_nine_cards() {
        assert_eq!(starter_pack().len(), 29);
    }
}
